# Generated by Django 5.0.6 on 2024-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_in_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('photos', models.ImageField(upload_to='Inventph/')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventorydata',
        ),
    ]
